Viz EC2 Services to Lambda - Part 1 - High Water Probability
NOAA-OWP/hydrovis pull request #543
Opened 2023-09-20 20:06 UTC by TylerSchrag-NOAA

This PR migrates the ensemble-based High Water Probability products from the Viz EC2 to the Viz Max Values lambda function (now called Python Preprocessing). It broadly encapsulates the following changes:

**Changes**
- Renaming of the Viz Max Values lambda function to Viz Python Preprocessing
- Renaming of max_values (and variations) to python_preprocessing throughout code base
- Abstraction of python_preprocessing to function to include multiple "products", with max_values now being one of those products.
- New high_water_probability product script that supports both 12 hour SRF and 5 day GFS MRF configurations.

**Testing** - I've tested this new functionality with SRF, MRF, and ANA configurations fairly vigorously in the dev historic event version of the pipelines, which was created in August 2023. That said, I have not tested it with coastal configurations, which do rely on max_values for FIM preprocessing. I have also not thoroughly tested the actual map service component on the EGIS, as I cannot access the portal. I believe it's close enough to deploy to TI for testing this functionality.

**Deployment Considerations:**
- We should definitely wait until the upcoming public release deployment is well and settled before merging this into TI, as it includes foundational changes to the pipelines that we do not want to contend with for hot fixes.
- We will need to include a ingest schema db dump when deploying to UAT.

2023-09-21 20:08 UTC, shawncrawley approved these changes
This looks good - and it is super cool to be moving that much closer to no more EC2 pipeline processing! Well done.

2023-09-27 15:39 UTC, CoreyKrewson-NOAA requested changes

2023-09-27 17:24 UTC, shawncrawley commented on Core/LAMBDA/viz_functions/viz_initialize_pipeline/lambda_function.py
> +                self.python_preprocessing.extend([python_preprocess for python_preprocess in product['python_preprocessing'] if python_preprocess not in self.python_preprocessing])
I feel like I like it. I'm always on the fence a bit myself around these same exact configuration questions. If we add a new configuration option, I realize that it's annoying to have to spell out every pre-existing use of the now-option just for the sake of the one-off that the option was now created for. But you do always lose a bit of transparency with under the cover defaults. But I still think I lean toward the defaults existing so the option does not need to be spelled out everywhere.

2023-09-27 17:26 UTC, CoreyKrewson-NOAA commented on Core/LAMBDA/viz_functions/viz_initialize_pipeline/lambda_function.py
> +                self.python_preprocessing.extend([python_preprocess for python_preprocess in product['python_preprocessing'] if python_preprocess not in self.python_preprocessing])
yeah I go back and forth as well. I do think we need to chose one and stick with it for consistency. I lean towards using defaults but making sure we have a template that is up to date and clear

2023-09-27 17:28 UTC, shawncrawley commented on Core/LAMBDA/viz_functions/viz_initialize_pipeline/lambda_function.py
> +                self.python_preprocessing.extend([python_preprocess for python_preprocess in product['python_preprocessing'] if python_preprocess not in self.python_preprocessing])
Agreed. Especially on the well-documented template.

2023-09-28 17:45 UTC, CoreyKrewson-NOAA commented on Core/LAMBDA/viz_functions/viz_initialize_pipeline/lambda_function.py
> +                self.python_preprocessing.extend([python_preprocess for python_preprocess in product['python_preprocessing'] if python_preprocess not in self.python_preprocessing])
I realized that some other python_preprocessing args are technically (or could be) optional but we require it. I am just going to leave this as is for now and keep it required to stay consistent

2023-09-28 17:45 UTC, CoreyKrewson-NOAA approved these changes

2023-09-28 17:47 UTC, merged